---
title: "02-Habitat"
author: "Francisco E. Fonturbel"
date: "19/nov/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

## Anthropogenic effects on chungungo's abundance

Here we will explore some anthropogenic variables as potential drivers os abundance change on this species

```{r data, include=FALSE}
#loading libraries
library(mgcv)
library(lme4)
library(lmerTest)
library(pbkrtest)
library(MuMIn)
library(MCMCglmm)
library(ggplot2)
source("multiplot.R")

#loading data
data<-read.table("data/data.txt", header = T)
attach(data)

hab<-read.table("data/habitat.txt", header = T)

#ggplot grooming
My_Theme = theme(
  axis.title.x = element_text(size = 18,face="bold"),
  axis.text.x = element_text(size = 16),
  axis.text.y = element_text(size = 16),
  axis.title.y = element_text(size = 18,face="bold"),
  legend.text = element_text(size = 14),
  legend.title = element_text(size = 14,face="bold"),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  panel.background = element_rect(fill = "white"),
  plot.title = element_text(size = 24,face = "bold", hjust=0.5))
```

We have characterized six sites where _Lontra felina_ is present

## Session

```{r session, echo=T}
sessionInfo()
```